@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIlJvbGUiOiJBZG1pbiIsIlVzZXJJZCI6IjkzZjU2MDYyLWI1ODktNDJhMi0zYjQ3LTA4ZGI2ZmI5MWQ2ZCIsIklpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY4ODIxMjQwNSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkifQ.Po9jnHpD2xElibSfU2_cEA0Kt9AtL9PvW2xQ1x9QSVw


@Id=7e4f5b4c-8d7e-464b-0fe9-08db6d83e7b4
@Iid=2
###
//get all list and auth
GET https://{{host}}/api/Courses/AllCourseList
Authorization: Bearer {{accessToken}}

###
#Get Courser Details
GET https://{{host}}/api/Courses/FindCourse/{{Id}}

###
#list of Couser in That Institute
GET https://{{host}}/api/Courses/InstituteCourses/{{Iid}}
###
#Add Course using Institute Id
POST https://{{host}}/api/Courses/AddCourse/{{Iid}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "courseName": "B.Tech",
  "departmentName": "IT"
}
###
#update Course Details
PUT https://{{host}}/api/Courses/Update/{{Id}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "courseName": "B.Tech",
  "departmentName": "CSE"
}
###
#Delete Course Details
DELETE https://{{host}}/api/Courses/Delete/{{Id}}}
Authorization: Bearer {{accessToken}}
