@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY4NjkxNjAyNSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkifQ.kkYGsVU-b7QqW2CgkVEfNiZlpNwzNuO4rvQEu4TDEc0


@Cid=7e4f5b4c-8d7e-464b-0fe9-08db6d83e7b4
@Stid=11c71beb-bde7-46e0-5725-08db6d833c1b
#list of Enroll Student
GET https://{{host}}/api/EnrollStudents/AllEnrollStudents
Authorization: Bearer {{accessToken}}

###
#list of student by Course
GET https://{{host}}/api/EnrollStudents/EnrollStudentsByCourse/{{Cid}}
Authorization: Bearer {{accessToken}}
###
#course id by Student Id
GET https://{{host}}/api/EnrollStudents/CourseIdByStudentId/{{Stid}}
Authorization: Bearer {{accessToken}}
###
#
POST https://{{host}}/api/EnrollStudents/AddEnrollStudent
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "courseId": "7e4f5b4c-8d7e-464b-0fe9-08db6d83e7b4",
  "studentId": "11c71beb-bde7-46e0-5725-08db6d833c1b"
}
###
#delete enroll student
DELETE https://{{host}}/api/EnrollStudents/DeleteEnrollStudent/{{Stid}}
Authorization: Bearer {{accessToken}}