@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY4NzA3NTMxMiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkifQ.1lSAmjwuJVMpGd4MCHbNpfIgr3SpZSgB-FjiENr3AoA

@Cid=1ff63a81-ef8e-42cc-83bb-08db6fba986b
@Stid=da0b0b35-6a96-43a7-3b49-08db6fb91d6d
#list of Enroll Student
GET https://{{host}}/api/EnrollStudents/AllEnrollStudents
Authorization: Bearer {{accessToken}}

###
#list of student by Course
GET https://{{host}}/api/EnrollStudents/EnrollStudentsByCourse/{{Cid}}
Authorization: Bearer {{accessToken}}
###
#course id by Student Id
GET https://{{host}}/api/EnrollStudents/CourseIdByStudentId/{{Stid}}
Authorization: Bearer {{accessToken}}
###
#
POST https://{{host}}/api/EnrollStudents/AddEnrollStudent
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "courseId": "1ff63a81-ef8e-42cc-83bb-08db6fba986b",
  "studentId": "da0b0b35-6a96-43a7-3b49-08db6fb91d6d"
}
###
#delete enroll student
DELETE https://{{host}}/api/EnrollStudents/DeleteEnrollStudent/{{Stid}}
Authorization: Bearer {{accessToken}}