@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY4Njk3NzEzNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkifQ.P6k-hrqa-9Crtx7Wr6mNfUDaiZQNE8-iE-DtCrkS4cY


@Id=1e619014-18a6-495f-50b2-08db6e473a7f
@Sid=30fffd79-2a77-4aa4-8599-08db6ed672ec

#list of all exam
GET https://{{host}}/api/ExamDetails/AllExamDetailsList
Authorization: Bearer {{accessToken}}

###
#Exam details list by subject ID
GET https://{{host}}/api/ExamDetails/ExamDetailsListBySubject/{{Sid}}
Authorization: Bearer {{accessToken}}
###
#Find Exam
GET https://{{host}}/api/ExamDetails/ExamDetail/{{Id}}
Authorization: Bearer {{accessToken}}
###
#add Exam
POST https://{{host}}/api/ExamDetails/AddExamDetail/{{Sid}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "examName": "Sem-2",
  "date": "08-12-2023",
  "time": "13:30",
  "duration": 20,
  "noOfQuestion": 20,
  "totalMark": 40
}
###
#
PUT https://{{host}}/api/ExamDetails/UpdateExamDetail/{{Id}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "examName": "Sem-1",
  "date": "08-12-2023",
  "time": "13:30",
  "duration": 20,
  "noOfQuestion": 20,
  "totalMark": 40
}

###
#Delete 
DELETE https://{{host}}/api/ExamDetails/DeleteExamDetail/{{Id}}
Authorization: Bearer {{accessToken}}