@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFtYW5AZ21haWwuY29tIiwiUm9sZSI6Ikluc3RpdHV0ZVVzZXIiLCJVc2VySWQiOiJjZjRkM2U2ZC0yYjk1LTQ4MTktMjg5ZS0wOGRiN2ExMjc0OTQiLCJJaWQiOiIxMCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ikluc3RpdHV0ZVVzZXIiLCJleHAiOjE2ODgzMTA1MzIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3Mjg5In0.60MFa-4oCWn_NC7jBP6A4gocVsi6VjZa4rgtmvGgZOQ

@Id=ec94c937-58a5-48b8-0d8b-08db6cb8df7b
@Sid=afb796bb-b519-4ee6-ace0-08db7a5da0a3
@Eid=4e890945-889e-4349-5724-08db6d833c1b

#GEt all Question List
GET https://{{host}}/api/Questions/AllQuestions
Authorization: Bearer {{accessToken}}
###
#Get Question By Question List
GET https://{{host}}/api/Questions/FindQuestion/{{Id}}
Authorization: Bearer {{accessToken}}
###
# list of Question by Subject Id
GET https://{{host}}/api/Questions/QuestionsListBySubject/{{Sid}}
Authorization: Bearer {{accessToken}}

###
#list of Question By Examiner
GET https://{{host}}/api/Questions/QuestionsListByExaminer/{{Eid}}
Authorization: Bearer {{accessToken}}
###
#Add Question Details
# Add Question by Subject and Examiner Id
POST https://{{host}}/api/Questions/AddQuestion?Sid={{Sid}}&Eid={{Eid}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "questionSet": 1,
  "questionTitle": "What is the full form of DBMS?",
  "option_A": "Data of Binary Management System",
  "option_B": "Database Management System",
  "option_C": "Database Management Service",
  "option_D": "Data Backup Management System",
  "correctOption": "B",
  "mark": 4
}
###
#Add Question Details
# Add Question by Subject and Examiner Id
POST https://{{host}}/api/Questions/AddQuestion?Sid={{Sid}}&Eid={{Eid}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "questionSet": 1,
  "questionTitle": "Who created the first DBMS?",
  "option_A": "Edgar Frank Codd",
  "option_B": "Charles Bachman",
  "option_C": "Charles Babbage",
  "option_D": "Sharon B. Codd",
  "correctOption": "B",
  "mark": 4
}
###
#Update Detils Question
PUT https://{{host}}/api/Questions/UpdateQuestion/{{Id}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "questionSet": 1,
  "questionTitle": "string",
  "option_A": "string",
  "option_B": "string",
  "option_C": "string",
  "option_D": "string",
  "correctOption": "C",
  "mark": 0
}
###
#Delete Question
DELETE https://{{host}}/api/Questions/DeleteQuestion/{{Id}}
Authorization: Bearer {{accessToken}}