@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY4Njk3NzEzNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkifQ.P6k-hrqa-9Crtx7Wr6mNfUDaiZQNE8-iE-DtCrkS4cY

@Id=5681cb66-2662-4082-be87-08db6cbadff2
@Sid=aab5c98a-7fc7-43aa-d04b-08db6ed4cd60
@Eid=31497b28-aff0-4451-2249-08db6ed693a3
#list of Result
GET https://{{host}}/api/Results/ResultsList
Authorization: Bearer {{accessToken}}

###
#Result by result ID
GET  https://{{host}}/api/Results/ResultById/{{Id}}
Authorization: Bearer {{accessToken}}

###
#Result by student and exam id
#not user Of This
###GET  https://{{host}}/api/Results/ResultByStudentIdandExamId?sid={sid}&eid={eid}

###
#Result list by Student
GET  https://{{host}}/api/Results/ResultByStudentId/{{Sid}}
Authorization: Bearer {{accessToken}}

###
#Result list by Exam
GET  https://{{host}}/api/Results/ResultByExamId/{{Eid}}
Authorization: Bearer {{accessToken}}

###
#Add Result
POST https://{{host}}/api/Results/AddResult?sId={{Sid}}&eId={{Eid}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "totalMarks": 0,
  "marksObtained": 0,
  "obtainedPercentage": 0,
  "gradeObtained": "A+"
}
###
DELETE  https://{{host}}/api/Results/DeleteResult/{{Id}}
Authorization: Bearer {{accessToken}}