@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY4NjkxOTAxMiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkifQ.iwJyUfIIsfU_55Bpd6li_g5HoFRxhwXuy7M1sJ214tA


@Cid=7e4f5b4c-8d7e-464b-0fe9-08db6d83e7b4
@Id=cf197054-8e3c-43da-4fa4-08db6e46cd09
#All subject List
GET https://{{host}}/api/Subjects/AllSubjectlist
Authorization: Bearer {{accessToken}}
###
#Subject List by Course Id
GET https://{{host}}/api/Subjects/subjectlistbycourse/{{Cid}}
Authorization: Bearer {{accessToken}}
###
#Subject Details By subject Id
GET https://{{host}}/api/Subjects/FindSubject/{{Id}}
Authorization: Bearer {{accessToken}}
###
#Add Subject using Course Id
POST https://{{host}}/api/Subjects/AddSubject/{{Cid}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "subjectCode": "DSA-801",
  "subjectName": "Data"
}
###
#Update Course Details
PUT https://{{host}}/api/Subjects/Update/{{Id}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "subjectCode": "DSA",
  "subjectName": "Data"
}
###
#Delete Subject
DELETE https://{{host}}/api/Subjects/Delete/{id}