@hostname=localhost
@port=7289
@host={{hostname}}:{{port}}
@contentType = application/json
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIlJvbGUiOiJBZG1pbiIsIlVzZXJJZCI6IjkzZjU2MDYyLWI1ODktNDJhMi0zYjQ3LTA4ZGI2ZmI5MWQ2ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL3NpZCI6IjkzZjU2MDYyLWI1ODktNDJhMi0zYjQ3LTA4ZGI2ZmI5MWQ2ZCIsImV4cCI6MTY4NzI5MzIzMSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyODkifQ.hnyBgPQKJdVsWMwwWp7vQB-cTvWreah9JfCuWciY4TA


@Id=da0b0b35-6a96-43a7-3b49-08db6fb91d6d
@Iid=2
@roleId=4

#all user list
GET https://{{host}}/api/Users/Userlist
Authorization: Bearer {{accessToken}}

###
#userlist by Institute Id
GET https://{{host}}/api/Users/UserlistByInstituteId/{{Iid}}
Authorization: Bearer {{accessToken}}
###
#find user by user ID 
GET https://{{host}}/api/Users/UserFind/{{Id}}
Authorization: Bearer {{accessToken}}

###
#Sign UP in data base
POST https://{{host}}/api/Users/Signup?roleId={{roleId}}&instituteId={{Iid}}
Content-Type: {{contentType}}

{
  "fname": "Student",
  "lname": "User",
  "gender": "M",
  "dob": "23-11-1998",
  "email": "student@gmail.com",
  "phoneNumber": "8562713396",
  "password": "12345",
  "confirmPassword": "12345"
}
###
#Sign UP in data base
POST https://{{host}}/api/Users/Signup?roleId={{roleId}}&instituteId={{Iid}}
Content-Type: {{contentType}}

{
  "fname": "Student",
  "lname": "User",
  "gender": "M",
  "dob": "23-11-1998",
  "email": "student1@gmail.com",
  "phoneNumber": "8562713396",
  "password": "12345",
  "confirmPassword": "12345"
}
###
#Sign UP in data base
POST https://{{host}}/api/Users/Signup?roleId=3&instituteId={{Iid}}
Content-Type: {{contentType}}

{
  "fname": "Examiner",
  "lname": "User",
  "gender": "M",
  "dob": "23-11-1986",
  "email": "examiner@gmail.com",
  "phoneNumber": "8562713396",
  "password": "12345",
  "confirmPassword": "12345"
}
###
#Sign UP in data base //Admin
POST https://{{host}}/api/Users/Signup?roleId=1&instituteId=1
Content-Type: {{contentType}}

{
  "fname": "Admin",
  "lname": "User",
  "gender": "M",
  "dob": "23-07-1990",
  "email": "admin@gmail.com",
  "phoneNumber": "9080765634",
  "password": "Admin@123",
  "confirmPassword": "Admin@123"
}
###
#Update User Deatails
PUT https://{{host}}/api/Users/Update/{{Id}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "fname": "Admin",
  "lname": "User",
  "gender": "M",
  "dob": "23-07-1990",
  "email": "admin@gmail.com",
  "phoneNumber": "9080765634",
  "password": "Admin@123",
  "confirmPassword": "Admin@123"
}

###
#Login in
POST https://{{host}}/api/Users/Login
Content-Type: {{contentType}}

{
  "Email": "admin@gmail.com",
  "password": "Admin@123"
}
###
#DELETE user
DELETE https://{{host}}/api/Users/Delete/{{Id}}
Authorization: Bearer {{accessToken}}

###
#this for Activate Password
PUT https://{{host}}/api/Users/ActivatedStatus/{{Id}}
Authorization: Bearer {{accessToken}}



###
#update Password Only
#PUT https://{{host}}/api/Users/UpdatePassword/{userid}
#Content-Type: {{contentType}}
#Accept-Language: en-US,en;q=0.5
#{
#  "currentPassword": "string",
#  "newPassword": "string"
#}
#Authorization: Bearer {{accessToken}}
###